# Generated by Django 4.2.3 on 2023-09-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_NAME', models.CharField(max_length=50)),
                ('DESCRIPTION', models.CharField(max_length=500)),
                ('PUBLISH_DATE', models.DateField()),
            ],
        ),
    ]
