# Generated by Django 4.2.3 on 2023-09-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CATEGORY',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='IMAGE',
            field=models.ImageField(default='', upload_to='SHOP/IMAGES'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRICE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='SUBCATEGORY',
            field=models.CharField(default='', max_length=50),
        ),
    ]
