# Generated by Django 4.2.5 on 2023-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('MESSAGE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('EMAIL', models.CharField(default='', max_length=50)),
                ('PHONE', models.CharField(default='', max_length=50)),
                ('DESC', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
