# Generated by Django 4.2.5 on 2023-10-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CONTACT',
            new_name='CONTACTS',
        ),
    ]
