# Generated by Django 4.2.5 on 2023-10-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP', '0004_rename_contact_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CONTACTS',
            new_name='CONTACT',
        ),
    ]
